begin;
create index if not exists audit_logs_user_id_idx on public.audit_logs(user_id);
create index if not exists draw_pool_entries_modified_by_idx on public.draw_pool_entries(modified_by);
create index if not exists draw_sessions_conducted_by_idx on public.draw_sessions(conducted_by);
create index if not exists draw_sessions_cycle_id_idx on public.draw_sessions(cycle_id);
create index if not exists files_organization_id_idx on public.files(organization_id);
create index if not exists files_uploaded_by_idx on public.files(uploaded_by);
create index if not exists kuris_organization_id_idx on public.kuris(organization_id);
create index if not exists membership_exit_refund_transactions_processed_by_idx on public.membership_exit_refund_transactions(processed_by);
create index if not exists membership_exits_approved_by_idx on public.membership_exits(approved_by);
create index if not exists membership_exits_membership_id_idx on public.membership_exits(membership_id);
create index if not exists membership_exits_settled_to_nominee_id_idx on public.membership_exits(settled_to_nominee_id);
create index if not exists monthly_winners_finalized_by_idx on public.monthly_winners(finalized_by);
create index if not exists muppu_records_cycle_id_idx on public.muppu_records(cycle_id);
create index if not exists muppu_records_person_id_idx on public.muppu_records(person_id);
create index if not exists organization_users_user_id_idx on public.organization_users(user_id);
create index if not exists payment_allocations_allocated_by_idx on public.payment_allocations(allocated_by);
create index if not exists payments_proof_file_id_idx on public.payments(proof_file_id);
create index if not exists payments_verified_by_idx on public.payments(verified_by);
create index if not exists payouts_processed_by_idx on public.payouts(processed_by);
commit;